collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.8960574
color:
  saturation: 0.1090432
  brandStrength: 1
  lightness: 0.229222
  brandColors:
    - '#040203'
    - '#5C5327'
    - '#C6E176'
    - '#91A591'
    - '#88C842'
  rhythmicContrast: 0.9220014
layout_spectrum: 0.04121864
name: Nspired
