name: Nspired
favicon: null
layout_spectrum: 0.04121864
typography_spectrum: 0.8960574
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Nspired Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040203'
    - '#5C5327'
    - '#C6E176'
    - '#91A591'
    - '#88C842'
  brandStrength: 1
  lightness: 0.229222
  saturation: 0.1090432
  rhythmicContrast: 0.9220014
purpose: []
